@startuml

  Class Computadora{
    - String tipo

    void seleccionComponentes()
    void ensambladoComponentes()
    void instalacionSoftware()
    void empaquetado()
    void setTipo(string t)
    string getTipo()
    Tipo* factoryMethod() <<template>>

  }
  Class Creacion{
    Computadora* crear(int type)
  }
  Class Desktop{
    - Desktop();
  }
  Class Laptop{
    - Laptop();
  }
  Class Netbook{
    - Netbook();
  }
  Class Tablet{
    - Tablet();
  }
  Class Server_Rack{
    - Server_Rack();
  }
  Class Server_Tower{
    - Server_Tower();
  }

  Computadora <|-- Desktop
  Computadora <|-- Laptop
  Computadora <|-- Netbook
  Computadora <|-- Tablet
  Computadora <|-- Server_Rack
  Computadora <|-- Server_Tower
  Computadora <-- Creacion :crea

@enduml
