@startuml

  Class Computadora{
    - String tipo

    void seleccionComponentes()
    void ensambladoComponentes()
    void instalacionSoftware()
    void empaquetado()
    void setTipo(string t)
    string getTipo()
    Tipo* factoryMethod() <<template>>

  }
  Class Creacion{
    Computadora* crear(int type)
  }
  Class Desktop{
    friend class Computadora;
    - Desktop():Computadora();
  }
  Class Laptop{
    friend class Computadora;
    - Laptop():Computadora();
  }
  Class Netbook{
    friend class Computadora;
    - Netbook():Computadora();
  }
  Class Tablet{
    friend class Computadora;
    - Tablet():Computadora();
  }
  Class Server_Rack{
    friend class Computadora;
    - Server_Rack():Computadora();
  }
  Class Server_Tower{
    friend class Computadora;
    - Server_Tower():Computadora();
  }

  Computadora <|-- Desktop
  Computadora --> Desktop :returns
  Computadora <|-- Laptop
  Computadora --> Laptop :returns
  Computadora <|-- Netbook
  Computadora --> Netbook :returns
  Computadora <|-- Tablet
  Computadora --> Tablet :returns
  Computadora <|-- Server_Rack
  Computadora --> Server_Rack :returns
  Computadora <|-- Server_Tower
  Computadora --> Server_Tower :returns
  Computadora <-- Creacion :crea

@enduml
