version: "3.3"
services:
  mysql:
     image: mysql
     environment:
        MYSQL_USER: luis
        MYSQL_PASSWORD: luis
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: proyecto
     expose:
        - "3306"
     ports:
        - "3306:3306"
